FROM maven:3.9.9-eclipse-temurin-21-alpine AS build
WORKDIR /src
COPY . .
ENV MAVEN_OPTS="-Xmx256m"
RUN mvn -B -q clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /src/target/*.jar app.jar
COPY render-entrypoint.sh /app/render-entrypoint.sh
RUN chmod +x /app/render-entrypoint.sh
ENV PORT=8080
EXPOSE 8080
ENTRYPOINT ["/app/render-entrypoint.sh"]
