FROM maven:3.9.9-eclipse-temurin-21-alpine AS build
WORKDIR /src
COPY . .
ENV MAVEN_OPTS="-Xmx256m"
RUN mvn -B -q clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /src/target/*.jar app.jar
ENV PORT=8080
EXPOSE 8080
CMD ["java", "-Xms128m", "-Xmx256m", "-jar", "app.jar"]
