<?xml version="1.0" encoding="UTF-8"?>
<project name="ebuddy-j2me" default="host-jar" basedir=".">
  <property file="build.properties"/>
  <property name="build.classes" value="${build.dir}/host-classes"/>
  <target name="clean"><delete dir="${build.dir}"/><delete dir="${dist.dir}"/></target>
  <target name="host-compile">
    <mkdir dir="${build.classes}"/>
    <javac srcdir="${src.dir}" destdir="${build.classes}" source="1.7" target="1.7" includeantruntime="false" encoding="UTF-8">
      <classpath><pathelement location="${microemu.cldc}"/><pathelement location="${microemu.midp}"/></classpath>
    </javac>
  </target>
  <target name="host-jar" depends="host-compile">
    <mkdir dir="${dist.dir}"/>
    <jar jarfile="${dist.dir}/ebuddy.jar" manifest="MANIFEST.MF"><fileset dir="${build.classes}"/><fileset dir="${res.dir}"/></jar>
    <copy file="ebuddy.jad" tofile="${dist.dir}/ebuddy.jad"/>
  </target>
  <target name="jar" depends="host-jar"/>
</project>
