package com.ebuddy.service;
import com.ebuddy.domain.*; import com.ebuddy.repo.*; import com.ebuddy.web.*; import org.springframework.data.domain.PageRequest; import org.springframework.data.redis.core.StringRedisTemplate; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.Duration; import java.util.*; import java.util.stream.*;
@Service public class MessageService { final UserRepository users; final MessageRepository messages; final ReceiptRepository receipts; final OutboxRepository outbox; final StringRedisTemplate redis; public MessageService(UserRepository u,MessageRepository m,ReceiptRepository r,OutboxRepository o,StringRedisTemplate x){users=u;messages=m;receipts=r;outbox=o;redis=x;}
 private void online(UUID u){redis.opsForValue().set("presence:"+u,"online",Duration.ofMinutes(5));}
 @Transactional public ApiModels.MessageView send(UUID from,ApiModels.SendRequest r){online(from);UserEntity target=users.findById(r.toUserId()).orElseThrow(NotFoundException::new);if(target.getState()!=UserState.active)throw new ForbiddenException();var prior=messages.findBySenderUserIdAndClientMessageId(from,r.clientMessageId());if(prior.isPresent()){if(!prior.get().getBody().equals(r.body())||!prior.get().getRecipientUserId().equals(r.toUserId()))throw new ConflictException("Identifier was already used with different content");return view(prior.get());}MessageEntity m=messages.save(new MessageEntity(from,r.toUserId(),r.clientMessageId(),r.body()));outbox.save(new OutboxEntity(m.getId(),"message.created"));return view(m);}
 @Transactional public void receipt(UUID user,UUID id,String state){MessageEntity m=messages.findVisible(id,user).orElseThrow(NotFoundException::new);if(!m.getRecipientUserId().equals(user))throw new ForbiddenException();String before=m.getStatus().name();if("read".equals(state))m.markRead();else m.markDelivered();messages.save(m);var receipt=receipts.findByMessageIdAndRecipientUserId(id,user).orElseGet(()->new ReceiptEntity(id,user));if("read".equals(state))receipt.read();else receipt.delivered();receipts.save(receipt);if(!before.equals(m.getStatus().name()))outbox.save(new OutboxEntity(id,"message.status."+m.getStatus().name()));online(user);}
 @Transactional(readOnly=true) public List<ApiModels.MessageView> sync(UUID user,long cursor,int limit){online(user);return messages.findAfter(user,Math.max(0,cursor),PageRequest.of(0,Math.min(Math.max(limit,1),20))).stream().map(this::view).toList();}
 public ApiModels.MessageView view(MessageEntity m){return new ApiModels.MessageView(m.getId(),m.getSenderUserId(),m.getRecipientUserId(),m.getClientMessageId(),m.getSequence(),m.getBody(),m.getStatus().name(),m.getCreatedAt(),m.getDeliveredAt(),m.getReadAt());}
}
